### ISSUE TITLE
FEATURE: Display "Title" frontmatter if exists

### ISSUE THREAD

**Issue by karbassi** [marcjulianschwarz/obsidian-raycast#1]
Love this extension. I got it running on my machine.

It would be amazing to use the 'title' frontmatter if it exists over the filename. Thoughts?

**Comment by marcjulianschwarz** [comment]
Thank you, the extension is currently under review to be added to the official store. 

Now to your feature request, I would definitely like to include various methods for searching files (including the frontmatter if it exists).
I think these search methods might be useful:
- tag
- filename
- frontmatter -> maybe adding a preference field where you can specify which meta data you want to use for searching (e.g. "title")
- (creation date?)

And another feature that came to my mind right now would be to somehow make intern links searchable too. So if you search for a note, open it in the extensions "Quick Look" you can search through that notes links (this is only possible if the linked notes are all unique, which to my knowledge is always the case in Obsidian).
Let me know if this sounds interesting or not.

**Comment by marcjulianschwarz** [comment]
@karbassi you can now install the extension from the Raycast Store: https://www.raycast.com/marcjulian/obsidian

**Comment by marcjulianschwarz** [comment]
Didnt forget this issue.

I am having problems with the JS heap being out of memory when reading the content for every note (which would be necessary for everything listed here), especially for search related tasks.

See issue #19 for more info and further discussion.

**Comment by marcjulianschwarz** [comment]
Hi,

I thought a bit about this feature request and have some questions.

Do you have `title` in the frontmatter for every note in your vault? If yes, why did you add this key to the frontmatter?

Do you think it would make more sense to add parts of the yaml frontmatter to the metadata section of the command?

Should the user be able to "select" yaml keys in the preferences to be shown or should all yaml keys be shown at all times?

I am kind of struggling to implement this in a nice and useful way so that it is useable for everyone and not just for this one use case.
