### ISSUE TITLE
Feature Request: Edit obsidian .mds from inside Raycast?!?!

### ISSUE THREAD

**Issue by marketmann** [marcjulianschwarz/obsidian-raycast#22]
Hey there. 

I don't code and don't know if this is even possible, but...

If it is, then this would be amazing. 

Imagine how cool being able to edit obsidian notes from inside Raycast would be!

I would pay for this. I've been dreaming about pop-up notes inside spotlight for years.

Thanks! 

Rob. 

**P.S. Probably should of said this first: your extension is amazing. Thanks so much for making it.**

**Comment by marcjulianschwarz** [comment]
Hey there @marketmann.

Thank you for the nice feedback!
I think that this would definitely be possible. Will work on it and let you know when it is working.

**Comment by marcjulianschwarz** [comment]
Short demo for a workflow from note creation, note search, note edit, to open in Obsidian:

https://user-images.githubusercontent.com/67844154/174990180-5cfa8fd9-2480-439f-858b-f8b4c8b49855.mp4

Will probably need to fix a few minor issues and then it is ready to be released.

Any suggestions on what could be changed or added?
Thought about the ability to edit file names, this could however lead to issues with links in Obsidian that's why I am not so sure about it.

**Comment by marketmann** [comment]
Oh wow! Thanks for this!
