### ISSUE TITLE
Silent Mode not working

### ISSUE THREAD

**Issue by mikejongbloet** [marcjulianschwarz/obsidian-raycast#50]
Hey!

'Silent mode' doesn't seem to be working for me when using "Append to Daily Note". Even if I shut Obsidian down completely it still opens the application and note.

A bug perhaps?

**Comment by raphael314** [comment]
You need to go to the Obsidian extension "Advanced URI" and uncheck "Open file on write". Worked for me.

**Comment by raphael314** [comment]
Yeah, I see. I thought it worked for a moment, but I have the same problem now. Maybe if the "append" function would just edit the markdown file directly and not open Obsidian...

**Comment by marcjulianschwarz** [comment]
This is a limitation of the Obsidian Advanced URI plugin or to be more precise a limitation of the way daily notes work within Obsidian.
I am working on a general "Append" command which will work as smoothly as possible.

**Comment by t-buss** [comment]
@marcjulianschwarz any update on this?

For anyone finding this: When I was still running Linux, I solved this problem with a shell script that calls Rofi, see https://gist.github.com/t-buss/e7e16b1fc324c47b1900a0f83ea5c550 for the basic idea.
This is somewhat hacky, as in the script I copy the DailyNote.md from the templates folder manually without relying on Obsidian to create it. It might be hard to come up with a general solution that works with every vault setup, but it might be something that one can adapt him/herself for their own needs.

**Comment by KevinBatdorf** [comment]
I'm planning to rewrite the extension using Local REST Api ([Issue here](https://github.com/raycast/extensions/issues/16864)) which will prevent Obsidian coming into focus, but it will still require Obsidian to be opened (minimized or background is ok). That's because Obsidian limits plugins to only when it's open, and they don't have a native interface for when its closed (and I don't want to write something that interacts directly with the filesystem that could break on an obsidian update).

The main reason though is to build an AI extension so you can use your obsidian notes as a tool/agent with an upcoming Raycast feature, and not have it interrupt the session

> You need to go to the Obsidian extension "Advanced URI" and uncheck "Open file on write". Worked for me.

For me this still brings up Obsidian and focuses the app (just not the note).
